version: '3.8'

services:
    simple-webapp-front:
      build: ./example-frontend
      ports:
        -  "5000:5000"
      container_name: webbapp-front

    simple-webapp-back:
      build: ./example-backend
      environment:
        - REDIS_HOST=redis
      ports:
        -  "8080:8080"
      container_name: webapp-back

    redis:
      image: redis
      container_name: redis